### ISSUE TITLE
No streamlink-handoff link in the context menu since the last update

### ISSUE THREAD

**Issue by ishbutz** [bgh-github/streamlink-handoff#6] opened 2023-11-09 12:32 UTC
Your extension was working fine but since the last update (2.0.0), the streamlink-handoff icon is missing from firefox's context menu when I right click on a video link.

**Comment by bgh-github** [comment] 2023-11-10 08:47
Thanks for reporting @ishbutz . Everything seemed fine for me running v2 the days directly following the new release but I'm now having this same issue. Would you mind providing details on your platform and Firefox version please?

**Comment by bgh-github** [comment] 2023-11-10 12:38
This looks like it may be a combination of the the discussion/linked bugs at https://discourse.mozilla.org/t/strange-mv3-behaviour-browser-runtime-oninstalled-event-and-menus-create/111208 and potentially solved by the proposed enhancement at https://bugzilla.mozilla.org/show_bug.cgi?id=1842832.

The pattern when (re)installing seems that if the extension is installed from AMO _and_ the 'Allow this extension to run in Private Windows' dialog presented as part of the install is opted in to within a short space of time, the context menu is not properly initialised (Note: not reproducible sideloading via about:debugging)

Possible workaround: when installing the extension, if 'Allow this extension to run in Private Windows' is something you want enabled, leave the associated dialog open for 30+ seconds before clicking Okay to confirm the selection. This seems to allow sufficient time for the context menu to be initialised so as not to be interrupted by the private browsing option triggering a reload per the above Bugzilla link

**Comment by ishbutz** [comment] 2023-11-10 15:52
Thank you, it's back in the context menu! I just reinstalled the extension and it's working fine now. And I didn't have to re-do the host messaging setup which is good! (btw deactivate and reactivate the extension does not work, you have to reinstall it).

**Comment by bgh-github** [comment] 2023-11-12 00:47
That's good news. @ishbutz, just for reference, were the parts about private browsing (and if so, delaying the selection of that option) applicable in your case?

It does seem version 2 of the extension moving to Manifest V3 and relying exclusively on a `browser.runtime.onInstalled` listener for context menu creation has made it more fragile. I'm currently preparing an update that will hopefully improve robustness in this area.

**Comment by ishbutz** [comment] 2023-11-12 01:19
No, I didn't activate it in private browsing. And btw I forgot to tell you that I use Firefox dev edition and windows 10.

**Comment by bgh-github** [comment] 2023-11-12 01:43
No worries, thanks for that. I'll close this off as you're working again and extension version 2.0.1 was just released with additional context menu triggers.

**Closed as completed by bgh-github** 2023-11-12 01:43 UTC
